apiVersion: v1
entries:
  app1-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-02-25T13:29:58.614483383Z"
    description: A Helm chart for Kubernetes
    digest: 54ad2de6311158e1c564d984b1906a1a3b0a2976bd79d3c56af8cf19735ca348
    name: app1-chart
    type: application
    urls:
    - https://github.com/Lufe04/Helm_Repo/tree/main/charts/app1-chart-0.1.0.tgz
    version: 0.1.0
generated: "2025-02-25T13:29:58.613847445Z"
